### ISSUE TITLE
Doppelung Dokumentation

### ISSUE THREAD

**Issue by FreeInMind** [linuxmuster-docs/all-of-me#116]
Teile der (Sphinx) Dokumentation sind an zwei Stellen zu finden:
http://docs.linuxmuster.net/ und http://linuxmuster.net/doku/ 
Leider findet google oft letzteres, z.B. beim Stichwort linuxmuster-client-servertools ist der

-  erste Treffer http://linuxmuster.net/doku/howto_linuxclients/cloudclient.html

- der dritte Treffer ist erst der richtige http://docs.linuxmuster.net/de/latest/howtos/linuxclients/cloudclient.html

**Comment by zefanja** [comment]
Danke für den Hinweis. Das ist noch aus den Anfangszeiten der Sphinx-Doku. Ich weiß leider nicht wer zur Zeit für die Website verantwortlich ist, aber ich leite es weiter.

**Comment by jollyzsher** [comment]
Bei mir sind die ersten zehn google Treffer jetzt alle "falsch".
Noch am ehesten stimmt Treffer 9: http://lmn-docs.readthedocs.io/de/latest/clients/linuxclients/cloudclient.html
