### ISSUE TITLE
Pfade anpassen: NI-XenServer-Tools --> linuxmuster-hv-tool

### ISSUE THREAD

**Issue by FreeInMind** [linuxmuster-docs/all-of-me#118]
Durch die Umbennung der NI-XenServer-Tools in linuxmuster-hv-tool passt die Dokumentation bzgl Pfade nicht mehr (Siehe im Forum: https://ask.linuxmuster.net/t/konfiguration-automatisches-backup-fehler/1463 ).

Weiterhin ist das Repo https://github.com/linuxmuster/linuxmuster-hv-tools leer, d.h. aktuell kann man das  linuxmuster-hv-tool wohl nur bei der Installation des XenServer als SupplementalDisk installieren.  

Ich nehme an, die Umbennung wurde im Zuge der Umstellung von XenServer 6.5 auf 7.0 gemacht. Geklärt werden muss noch, ob die Pfade angepasst werden, wenn ein bestehender Xenserver von 6.5 auf 7.0 upgedatet wird.

**Comment by MachtDochNix** [comment]
Pfade in der Dokumentation angepasst.

Repo-Problem kann ich nicht lösen.

**Comment by zefanja** [comment]
Was die Doku betrifft, ist dieses Problem gelöst. Ich habe ein neues Ticket für das Repoproblem hier erstellt: https://github.com/linuxmuster/linuxmuster-hv-tools/issues/1
