### ISSUE TITLE
Windows 10 Benutzerprofil kopieren

### ISSUE THREAD

**Issue by jollyzsher** [linuxmuster-docs/all-of-me#46]
Anleitung muss geschrieben werden.

https://github.com/linuxmuster-docs/all-of-me/tree/master/source/howtos/windows10clients

@aloisr hat das gefunden

**Comment by jollyzsher** [comment]
screenshots fehlen
anleitung fertig

**Comment by zefanja** [comment]
Ist in Schritt 4 mit pgmadmin.SCHULE die Samba-Domain gemeint? Falls ja (was ich mal annehme) sollte da evtl. noch ein Hinweis hin, falls man bei der Installation eine andere eingerichtet hat.

**Comment by jollyzsher** [comment]
Hallo Alois,

hast du diese Nachricht auch bekommen?
Ich kann das nicht beantworten.

grüße, Tobias

Am 13.11.2016 um 13:51 schrieb zefanja:

**Comment by aloisr** [comment]
Habs entsprechen geändert.

Gruß

Alois

**Comment by zefanja** [comment]
Danke (fixed in c7beb57182313f6bc4ab8097ee696689963a5649)
