### ISSUE TITLE
check readthedocs dependency

### ISSUE THREAD

**Issue by jollyzsher** [linuxmuster-docs/all-of-me#61]
wir wollen keine Werbung
wir wollen CI

**Comment by zefanja** [comment]
Man kann mit Travis auch nach gh-pages deployen. Damit wäre die Werbung weg, aber auch das nette kleine Menü am unteren Rand...

**Comment by zefanja** [comment]
Ok, habe eben entdeckt, dass man die Werbung auch abschalten kann. Habe sie jetzt ausgeschalten. Ich fände es fair, wenn man vielleicht eine Gold Subscription machen könnte, dass es der LMN ja schon einiges an Mehrwert bietet.

Für eine custom domain (wie wir sie haben), gibt es einen Richtwert von 5$/Monat, 20$/Monat sind besser, sagen sie :)
