### ISSUE TITLE
release-info & upgrade should warn about Atheros chips

### ISSUE THREAD

**Issue by jollyzsher** [linuxmuster-docs/all-of-me#86]
discussion here: http://www.linuxmuster.net/forum/post/6815

c.) Gute Frage wegen der Kommunikation:
http://docs.linuxmuster.net/de/latest/release-information/…
steht eine Zeile
http://docs.linuxmuster.net/de/latest/howtos/upgrade/upgra…
ebenso.
Aber es sollte explizit eine Warnung oder Hinweis in die Release-Information und in die Upgrade-Anleitung, dass Atheros ein Problem hat. Damit man wenigstens vorgewarnt ist, dass man Turnschuhe brauchen könnte.

**Comment by zefanja** [comment]
Vielleicht können wir einen neuen Abschnitt machen, z.B. "Known Issues" oder "Known Problems" oder "FAQ" oder "Troubleshooting LINBO" whatever. Da könnte man diese Sache und andere hineinpacken.

**Comment by jollyzsher** [comment]
Ok. Ich habe das generisch für alle subthemen in die REleaseinfos aufgenommen. Inkl. Querverweis in den Upgrade-Anleitungen dass man die REleasenotes lesen muss.

**Comment by zefanja** [comment]
Danke dir. Vielleicht könnte man diese Seite noch woanders einordnen (nicht unter release-notes, sondern vielleicht unter howtos, misc oder faq?), da man dort auch noch viele andere wiederkehrende Probleme aufnehmen könnte (z.B. Probleme beim Drucken aus dem WLAN Netz, Probleme, die entstehen, wenn man eine IP aus 10.16.1.100-200 vergibt, etc.), also Probleme, die immer wieder auftauchen und wo man recht leicht eine Lösung finden kann, wenn man ein paar Sachen überprüft).

Sorry für meine Kleinigkeit, aber knowbugs als Dateiname trifft es finde ich nicht ganz, da es ja eher ein Bug in den Atheros-Karten zu sein scheint und nicht in LINBO. 

Danke für deinen Einsatz hier v.a. in den letzten Wochen @jollyzsher ! Du trägst sehr viel dazu bei, dass die Doku aktuell und in einem guten Zustand ist!
