### ISSUE TITLE
howto for openvpn

### ISSUE THREAD

**Issue by jollyzsher** [linuxmuster-docs/all-of-me#98]
- [ ] openvpn howto

OpenVPN wird nicht ganz einheitlich behandelt, 

im Handbuch gibt es Hinweise darauf:
  * http://www.linuxmuster.net/wiki/dokumentation:handbuch:printing:remoteaccess
  * http://www.linuxmuster.net/wiki/dokumentation:handbuch:preparation:preparations
  * http://www.linuxmuster.net/wiki/dokumentation:handbuch:maintenance:certificates.openvpn

Aber die hauptsächliche Dokumentation steht im Anwenderwiki:
  * http://www.linuxmuster.net/wiki/anwenderwiki:openvpn:start
  * http://www.linuxmuster.net/wiki/version3:openvpn (alt)

Im Handbuch sollte besser OpenVPN als Möglichkeit angesprochen werden und jedesmal mindestens auf das Anwenderwiki verlinkt werden - alternativ die Dokumentation aus dem Anwenderwiki ins Handbuch.

**Comment by cweikl** [comment]
Wenn wir openVPN in der Dokus für Lehrer beschreiben, dann würde ich alle drei links, die Du als Hinweise genannt hast, nicht aufnehmen. Ich würde nur darauf hinweisen, dass ein Drucken via VPN zunächst nicht vorgesehen ist, aber durch Anpassungen umgesetzt werden kann -> verlinken.

Teile von http://www.linuxmuster.net/wiki/anwenderwiki:openvpn:start könnte ich noch in die Doku einarbeiten. Die Einrichtung / Installation habe ich in der Doku beschrieben. Für die Nutzung könnten wir noch einige Hinweise geben. Für weitergehende Optionen würde ich auf das Wiki verweisen. Allerdings sind hier so viele Möglichkeiten beschrieben, dass wir in der Doku eine klare Vorgabe machen sollten und dann auf weitergehende Möglichkeiten nur verweisen. Das Ganze wird in der Doku sonst viel zu aufgebläht.

**Comment by jollyzsher** [comment]
Hi Christian,



Am 14.01.2017 um 12:08 schrieb Chris Weikl:
> Wenn wir openVPN in der Dokus für Lehrer beschreiben, dann würde ich
> alle drei links, die Du als Hinweise genannt hast, nicht aufnehmen. Ich
> würde nur darauf hinweisen, dass ein Drucken via VPN zunächst nicht
> vorgesehen ist, aber durch Anpassungen umgesetzt werden kann -> verlinken.

Super.


> 
> Teile von http://www.linuxmuster.net/wiki/anwenderwiki:openvpn:start
> könnte ich noch in die Doku einarbeiten. Die Einrichtung / Installation
> habe ich in der Doku beschrieben. Für die Nutzung könnten wir noch
> einige Hinweise geben. Für weitergehende Optionen würde ich auf das Wiki
> verweisen. Allerdings sind hier so viele Möglichkeiten beschrieben, dass
> wir in der Doku eine klare Vorgabe machen sollten und dann auf
> weitergehende Möglichkeiten nur verweisen. Das Ganze wird in der Doku
> sonst viel zu aufgebläht.

vollkommen richtig.
ich hab nur blind das ticket übernommen. So kurz wie möglich ist
richtig. Am Ende noch "Weiterführende Dokumentation" wäre super (wie bei
jedem anderen Howto auch noch nötig.)

Viele Grüße und Danke,
Tobias

**Comment by cweikl** [comment]
ok, habe ein pull request erstellt.

**Comment by cweikl** [comment]
Hi Tobias,

habe VPN überarbeitet und einen pull request erstellt. Der Merge Button 
taucht aber nicht mehr bei mir auf - obwohl es angeblich automatisch 
gemerged werden könnte ?!

Habe ich Tomaten auf den Augen, oder hat sich das geändert.

VG

Christian


Am 14.01.2017 um 12:46 schrieb T. Küchel:
> > 
> <https://github.com/linuxmuster-docs/all-of-me/issues/98#issuecomment-272617368>,

**Comment by jollyzsher** [comment]
Hi Christian,

bei mir taucht der Pull-request selbst nicht auf.
Da sowohl zefanja als auch ich ein paar Typos korrigiert und eingecheckt
haben:
kannst du nochmal prüfen, ob du den nochmal erstellen kannst?
Am besten nochmal
git stash
git pull upstream master
git stash pop
ausführen, falls unsere Änderungen bei dir nicht angekommen sind.
(hoffe, die reihenfolge ist richtig)

(zefanja hat den dateinamen .png.png gefixt, so dass es keine
Fehlermeldungen mehr gibt und ich habe ein paar Typos und URLs angepasst)

VG, Tobias

Am 14.01.2017 um 13:45 schrieb Chris Weikl:

**Comment by cweikl** [comment]
Hallo Tobias,

hatte ich vorher alles gemacht. Hab den Fehler gefunden.

Habe nun gemerged.

VG
Christian
Am 14.01.2017 um 14:21 schrieb T. Küchel:
